DataDog/watermarkpodautoscaler

cmd/manager/main.go
The Controller should not be able to create a service for monitoring purposes.
We are using annotations on the controller using autodiscovery to scrape the prometheus endpoint of the Controller.
=> remove the function call that try to create metrics service resource

README.md
In preparation of the Kubernetes Enhancement Proposal we need to officially move the controller to Beta.
=> Moving WPA to beta for the KEP

deploy/clusterrole.yaml, pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go
- Adding rights on event to CR 
The out of the box CR is missing the verb patch for events which yields:
```
E0127 20:43:23.071157       1 event.go:237] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"watermar [...] is forbidden: User "system:serviceaccount:default:watermarkpodautoscaler" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
```
- Add logic to not crash if target does not exist, as raised here https://github.com/DataDog/watermarkpodautoscaler/issues/43
=> Fix RBAC & Scale Target missing

pkg/controller/watermarkpodautoscaler/replica_calculator.go, pkg/controller/watermarkpodautoscaler/replica_calculator_test.go, pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go
With the current logic, the selector used to retrieve the number of pods of the target to only use the healthy ones in the calculation of the recommendation, relies on the selector exposed by the `Scale` interface.
This selector is the one in the matchSelector in the target deploy (or sts). The issue is that this selector can be shared by multiple targets.
Therefore, you can end up in a scenario where the Target has 5 replicas and as we try to see how many out of these 5 are healthy using the pod informer, if multiple deployments have the same selector, we might see 18 pods.
The solution is to check the owner ref as well to make sure we only look at the pods that relate to the target we are autoscaling.
=> Fixing the pod informer selector 

deploy/operator.yaml, pkg/controller/watermarkpodautoscaler/metrics.go, pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go
- Add an env var `DD_LABELS_AS_TAGS` that will add space-separated label keys as metric tags using label joins (with the wpa name label).
- Provides sample configuration in operator.yaml accordingly
To test:
- add desired labels in WPA CR
- update `DD_LABELS_AS_TAGS` and prometheus check configuration in operator.yaml
- confirm labels are present in prometheus metrics and tags are present in Datadog prometheus check output
=> add labels_info metric to support additional labels as tags

.gitlab-ci.yml
```
$ mkdir -p .cache
$ make install-tools
go build -o bin/yq ./vendor/github.com/mikefarah/yq/v3
make: go: Command not found
Makefile:101: recipe for target 'bin/yq' failed
make: *** [bin/yq] Error 127
Running after_script
00:01
Uploading artifacts for failed job
00:01
ERROR: Job failed: exit code 1
```
before script should not be run in the release step.
=> Fixing release step in gitlab pipeline

pkg/controller/watermarkpodautoscaler/metrics.go, pkg/controller/watermarkpodautoscaler/replica_calculator.go, pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go
Pass the right metric contexts to make sure we clean up the metrics correclty
The following metrics were not deleted when deleting the corresponding Custom Resource
- wpa_controller_high_watermark
- wpa_controller_low_watermark
- wpa_controller_restricted_scaling
- wpa_controller_value
=> Fix metrics cleanup

pkg/controller/watermarkpodautoscaler/replica_calculator.go, pkg/controller/watermarkpodautoscaler/replica_calculator_test.go
For a pod stuck in Pending that has been scheduled the starttime is == to the last transitiontime for the readiness.
Thus, it would always appear tolerated ready with the former formula.
*The goal is to ignore pods that are not even schedulable and to tolerate those who are in the process of starting for a duration of readynessDuration, defaulting to 10s.*
Ex:
Pod stuck in ContainerCreating:
```
status:
conditions:
- lastProbeTime: null
lastTransitionTime: "2020-08-26T22:30:14Z"
status: "True"
type: Initialized
- lastProbeTime: null
lastTransitionTime: "2020-08-26T22:30:14Z"
message: 'containers with unready status: [postgres]'
reason: ContainersNotReady
status: "False"
type: Ready
- lastProbeTime: null
lastTransitionTime: "2020-08-26T22:30:14Z"
message: 'containers with unready status: …
```
=> Fixing computation of schedulable pods stuck in Pending

chart/watermarkpodautoscaler/templates/clusterrole.yaml
Sync rules from `deploy/clusterrole.yaml` to `chart/watermarkpodautoscaler/templates/clusterrole.yaml`, note that we don't request `get` verb which is probably ok for what we need.
Working RBAC in helm chart.
Ensure there are no logs similar to:
```
E0902 18:04:45.304836       1 reflector.go:123] pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go:73: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:wpacontroller-watermarkpodautoscaler" cannot list resource "pods" in API group "" at the cluster scope
```
=> [wpa helm chart] Add missing rule for Pods in ClusterRole in helm chart

chart/watermarkpodautoscaler/Chart.yaml, chart/watermarkpodautoscaler/templates/deployment.yaml, chart/watermarkpodautoscaler/values.yaml
Updates chart for configuring labels as metric tags from #57 
Better user experience
Test Datadog prometheus check output (i.e. the tags) for WPA metrics with and without `labelsAsTags` set in values.yaml
=> add labelsAsTags to chart template

chart/watermarkpodautoscaler/Chart.yaml, chart/watermarkpodautoscaler/templates/deployment.yaml, pkg/controller/watermarkpodautoscaler/metrics.go, pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go
Update of #57, also use namespace label for matching and remove `label_to_match` in favor of `labels_to_match`
Better matching to safeguard against WPAs with the same name
Deprecation of `label_to_match` in the [open metrics check](https://github.com/DataDog/integrations-core/blob/8b034772fcacf21284c3bc5b4e92a16f56e0ae6b/datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py#L468)
Similar to #57
=> Updates to info metric

controllers/metrics.go, controllers/watermarkpodautoscaler_controller.go
When using several metrics as input, we now expose several Prometheus metrics `replicas_scaling_proposal`.
When using several metrics in input, `replicas_scaling_proposal` only reflects the last one defined in k8s' `spec.metrics`.
=> Add metric_name label to the replicas_scaling_proposal

api/v1alpha1/watermarkpodautoscaler_default.go, api/v1alpha1/watermarkpodautoscaler_types.go, api/v1alpha1/zz_generated.deepcopy.go, api/v1alpha1/zz_generated.openapi.go, chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd.yaml, config/crd/bases/v1beta1/datadoghq.com_watermarkpodautoscalers.yaml, controllers/replica_calculator.go, controllers/replica_calculator_test.go
This change exposes a new configuration option, `ReplicaScaleInterval` which controls how many replicas will be added at a time. When calculating the desired replicas, we use the existing algorithm to determine the desired number of replicas, and then we round _up_ to the nearest `ReplicaScaleInterval`. 
I didn't touch the interaction with the maxReplicas at all, so if your `maxReplicas` value is not divisble by the `ReplicaScaleInterval`, the max will win. 
I want to use WPA with kafka, with a specific number of replicas at any given moment. This change would allow us to always have a number of replicas that is divisible by 3, 5, etc.
The churn in `api/v1alpha1/zz_generated.openapi.go` doesn't seem quite right to me, I ran `make generate` and that came out. 
I want this to have a default …
=> Scale replicas by a configurable interval

api/v1alpha1/watermarkpodautoscaler_types.go, bundle/manifests/datadoghq.com_watermarkpodautoscalers.yaml, config/crd/bases/v1beta1/datadoghq.com_watermarkpodautoscalers.yaml
Update the ` +kubebuilder:printcolumn` on top of `type WatermarkPodAutoscaler struct `
```golang
// +kubebuilder:printcolumn:name="dry-run",type="string",JSONPath=".status.conditions[?(@.type==\"DryRun\")].status"
// ...
type WatermarkPodAutoscaler struct 
```
Fix WPA dry-run status in kubectl output.
Create a WPA without the dry-run mode. the `dry-run` status with `kubectl get wpa` should be equal to `false`
=> Fix WPA dry-run status in kubectl output

controllers/watermarkpodautoscaler_controller.go, controllers/watermarkpodautoscaler_controller_test.go
The core change here is removing  `now = metricTimestamp`
The timestamp of the datapoint of a metric **should not** be used as reference to compute whether we are allowed to scale.
What will happen is if the metric is 90s old (which is within range of acceptability) comparing the LastScalingTime to it and to the forbidden windows gives an incorrect result.
See the example `Forbidden window uses the right timestamp` in the tests.
Also fixed the tests, without the Reactor (get specifically) we would get empty objects, so everything would pass because it would be comparing nil objects.
Fix bug.
=> Fix bug pertaining to timestamp override

chart/watermarkpodautoscaler/templates/deployment.yaml, chart/watermarkpodautoscaler/values.yaml
Remove the `command` field in the Deployment manifest.
in v0.3 the controller binary has been renamed from `watermarkpodautoscaler` to `manager`. Since the `CMD` is defined in the dockerfile, the `command` field is not needed in the PodTemplate.
N/A
Try to deploy the last RC with the chart present in the `v0.3` branch. the controller should start.
=> Fix helm chart for v0.3 release

chart/watermarkpodautoscaler/templates/clusterrole.yaml, chart/watermarkpodautoscaler/templates/role.yaml, config/rbac/role.yaml, controllers/watermarkpodautoscaler_controller.go
Add missing RBAC to be able to scale specific Openshift resources: `DeploymentConfig` and `ReplicationController`
Fix the support of `DeploymentConfig` on openshift
This should fix #69 
N/A
* deploy the wpa controller on openshift.
* create a dummy DeploymentConfig resource
```yaml
apiVersion: v1
kind: DeploymentConfig
metadata:
name: hello-openshift
spec:
replicas: 1
selector:
app: hello-openshift
template:
metadata:
labels:
app: hello-openshift
spec:
containers:
- name: hello-openshift
image: openshift/hello-openshift:latest
ports:
- containerPort: 80
strategy:
type: Rolling   
```
* create a WPA target this DeploymentConfig
```yaml
apiVersion: datadoghq.com/v1alpha1
kind: WatermarkPodAutoscaler
metadata:
name: hello-openshift
spec:
maxReplicas: 10
minReplicas: 2
tolerance: 0.01 …
```
=> Fix DeploymentConfig support on openshift

.github/workflows/validation.yaml
Use `helm/kind-action` instead of `engineerd/setup-kind` for e2e GH actions.
Stability.
E2E tests are green.
=> [CI] Switch to helm/kind GH action

controllers/replica_calculator.go
Fixes logging of the tolerance % in several messages. It was printed like this: `"tolerance (%):":1`
Logging messages about the watermarks should report the tolerance % following this format: `"tolerance (%):1` instead of `"tolerance (%):":1`.
=> Fix logging of tolerance % in ReplicaCalculator

api/v1alpha1/watermarkpodautoscaler_default.go
=> [refactor] Use defined MetricSource types instead of strings

api/v1alpha1/watermarkpodautoscaler_types.go, config/crd/bases/v1beta1/datadoghq.com_watermarkpodautoscalers.yaml, controllers/watermarkpodautoscaler_controller.go, controllers/watermarkpodautoscaler_controller_test.go
Adds new columns to the `kubectl get wpa` output:
- `condition` ("ScalingActive", "AbleToScale", "ScalingLimited")
- `condition status` (true or false)
- `last scale` (time passed since last scale).
To be able to show the latest condition, I needed to keep them sorted. That's why `kubectl get wpa -o yaml` will now always show them sorted by "LatestTransitionTime" (most recent first).
Deploy an WPA. Check that the 3 new columns mentioned above appear in `kubectl get wpa` and show correct information. For `condition` and `condition status`, you can check that the one shown corresponds to the most recent condition shown in `kubectl get wpa -o yaml`.
=> Add latest condition and latest scale to `kubectl get wpa` output

api/v1alpha1/watermarkpodautoscaler_types.go, api/v1alpha1/zz_generated.openapi.go, chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd.yaml, config/crd/bases/v1beta1/datadoghq.com_watermarkpodautoscalers.yaml, hack/install-kubebuilder.sh
* Fix CRD definition to pass the open-api validation
* Update CRD manifest in the helm chart.
* fix kubebuilder download link
When we tried to deploy the current CRD from the main branch with `make deploy` the following was returned by the api server
```
Error: CustomResourceDefinition.apiextensions.k8s.io "watermarkpodautoscalers.datadoghq.com" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[metrics].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set, spec.validation.openAPIV3Schema.properties[status].properties[conditions].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set, …
```
=> Fix CRD definition and validation

api/v1alpha1/watermarkpodautoscaler_types.go, controllers/test/watermarkpodautoscaler_controller_test.go, controllers/test/watermarkpodautoscaler_e2e_test.go, controllers/watermarkpodautoscaler_controller.go, controllers/watermarkpodautoscaler_controller_test.go
* This PR remove the initialisation of `metricStatuses` to an empty
slice. like this the status should be created.
* Fix end2end test to cleanup properly resources, to allow the deletion of the test namespace.
In specific configuration if the status is empty (new WPA) in dry
run mode, and if `currentReplica` > max or < min, the status is not
created properly because wpa.status.CurrentMetrics is a empty slice
but not a nil slice.
Possible test scenario:
* create a deployement with a replicas value = 5
* create wpa targeting the deployment with a maxValue = 3 and dryRun mode
enabled.
Results:
* The WPA status should be created.
* No logs like like: `is invalid: status.currentMetrics: Required value`.
=> fix: allow wpa status update even if dry-run:true

controllers/replica_calculator.go, controllers/replica_calculator_test.go
With the current logic, if the metric is above the high watermark but you have some unready replicas, you can end up with fewer replicas than originally.
This is a problem for applications that take time to be ready for instance as it allows effectively downscaling when the scenario ought to yield a scale up event.
The expectation here is that even if some pods never become ready, we will keep at least as many pods as the status of the target has and this until the recommendation becomes higher than the current number of ready replicas.
I also fixed some tests that reflected this (incorrect, but designed) behavior. 
Better support for edge cases
if you have 5 ready replicas out of 10 in the spec of your deployment, 5 is used to compute the recommendation (based on the ratio of value/High …
=> Prevent downscale when value over HWM if some pods are unready

controllers/test/suite_test.go, controllers/watermarkpodautoscaler_controller.go, main.go
Will allow to create threads to consume from the workerqueue.
With a high number of objects, it allows faster reconciliation loop by using more goroutines.
This is a native controller runtime feature.
Verify that with a high number of WPAs to process the queue depth and duration decreases (with ~50 WPAs going from 1 to 4 workers)
=> Expose option to specify number of workers

api/v1alpha1/watermarkpodautoscaler_types.go, api/v1alpha1/zz_generated.openapi.go, config/crd/bases/v1beta1/datadoghq.com_watermarkpodautoscalers.yaml, controllers/replica_calculator.go, controllers/replica_calculator_test.go, controllers/watermarkpodautoscaler_controller.go, controllers/watermarkpodautoscaler_controller_test.go
Adds an option to specify the minimum percentage of pods from a target that need to be available in order for the controller to scale a target.
Note that the amount of ready replicas does not take into account replicas that are not properly labled (e.g. we only consider the replicas from the target in the WPA spec). We also consider replicas in pending during `ReadinessDelaySeconds` s.
Better control of edge cases. Works as a fast fail.
Scale rapidly a deployment that takes a long time to be marked available (use the probes) with a high ReadinessDelaySeconds to make sure that the controller stops if there are too many pending replicas.
=> Introduce option to specify minimum ratio of available pods

cmd/kubectl-wpa/app/dryrun/dryrun.go
Improve UX of the new WPA plugin.
1/ Fix the revert help example and add a more explicit usage.
2/ revert with no/wrong input would hang as it required a file but there was no check.
3/ `kubectl wpa dry-run` should be used in conjunction with a subcommand. Return the help if it's missing a subcommand
4/ if the saved stated csv is malformed do not default to false and also print a warning.
part of the WPA 0.4.0 QA.
=> Fix wpa plugin

.github/workflows/codeql-analysis.yml
Static code analysis on watermarkpodautoscaler using Github's Code Scanning.
This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to master branch. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later. It is a part of Datadog compliance requirements to regularly perform code-scanning on all the customer installed code. As the repository is small, no security alerts were found during the scan.
=> Setting up code scanning on watermarkpodautoscaler

controllers/metrics.go, controllers/watermarkpodautoscaler_controller.go, controllers/watermarkpodautoscaler_controller_test.go
Fix the `dryRun` status condition update.
the controller was setting the `dryRun` condition to early in the reconcile function.
At that time the `originalStatus` wasn't created (deepCopy). So when the function 
`updateStatusIfNeeded()` was comparing the `wpa.Status` with the  `originalStatus`
it didn't seen any different, so no WPA.status update was triggered.
Only if another element in the `status` was modify at the same time, was triggering
and update of the `dryRun` status condition.
Improve WPA UX, by returning valid information in the WPA status.
create a dummy deployment like: 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: redis
spec:
replicas: 1
selector:
matchLabels:
app: redis
template:
metadata:
labels:
app: redis
spec: …
```
=> fix: dryrun status not up-to-date

controllers/replica_calculator.go
Use a more performance approach to retrieve the Deployment name from a ReplicaSet name
benchmark used to compare it. (thanks @L3n41c)
```
$ go test --bench .
goos: darwin
goarch: amd64
pkg: parse_string_bench
cpu: Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
Benchmark_parseWithSplit-8   	 9194378	       138.5 ns/op
Benchmark_parseWithRegex-8   	 2668801	       418.2 ns/op
Benchmark_parseLastIndex-8   	330009844	         3.422 ns/op
PASS
ok  	parse_string_bench	4.517s
```
```golang
package main
​
import (
"regexp"
"strings"
"testing"
​
"github.com/stretchr/testify/assert"
)
​
var re = regexp.MustCompile("(.*)-.*")
​
func parseWithSplit(s string) string {
sp := strings.Split(s, "-")
sp = sp[:len(sp)-1]
return strings.Join(sp, "-")
}
​
func …
```
=> fix: improves checkOwnerRef func perf

api/v1alpha1/watermarkpodautoscaler_types.go, bundle/manifests/datadoghq.com_watermarkpodautoscalers.yaml, chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd.yaml, config/crd/bases/v1beta1/datadoghq.com_watermarkpodautoscalers.yaml, controllers/watermarkpodautoscaler_controller.go
* Add new additional colum `Scaling Active` on the WPA kubectl ouput.
* Re-generate the WPA CRD and bundle after PR #140 
The PR https://github.com/DataDog/watermarkpodautoscaler/pull/140 haven't updated the generated CRD manifest and bundle
=> fix: update CRD definition + add ScalingActive in status

Makefile, api/v1alpha1/watermarkpodautoscaler_types.go, api/v1alpha1/zz_generated.openapi.go, chart/watermarkpodautoscaler/CHANGELOG.md, chart/watermarkpodautoscaler/Chart.yaml, chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd_v1.yaml, chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd_v1beta1.yaml, config/crd/bases/v1/datadoghq.com_watermarkpodautoscalers.yaml
Add a new CRD to support 1.22. Update the chart.
Following the same pattern of the Datadog-Operator.
The chart will be moved to the [Datadog Helm Repo](https://github.com/DataDog/helm-charts) next.
Support users in Kubernetes 1.22
Issue initially brought up by our users https://github.com/DataDog/watermarkpodautoscaler/issues/135 
I had to move list types from set to atomic. 
Discuss if you believe this will have unintended effects.
Had to do it as x-kubernetes-types are supposed to be supported with k8s 1.16, so I did not want to just patch the chart (like we do for v1beta1). Set did not pass:
```
Error: INSTALLATION FAILED: CustomResourceDefinition.apiextensions.k8s.io "watermarkpodautoscalers.datadoghq.com" is invalid: spec.validation.openAPIV3Schema.properties[status].properties[curren …
```
=> Add new CRD to support Kubernetes 1.22

controllers/metrics.go, controllers/replica_calculator.go, controllers/watermarkpodautoscaler_controller.go
* Add `wpa_name` and `wpa_namespace` as log attributes to logs from the `controllers.WatermarkPodAutoscaler` logger. Currently, there is a `watermarkpodautoscaler` attribute that shows the `<wpa_namespace>/<wpa_name>` in logs.
* Add `wpa_namespace` as a tag to WPA metrics. The `resource_namespace` label also shows the namespace, but the naming is not intuitive.
More easily filter by WPA and WPA namespace in dashboards and graphs.
To use the `wpa_name` and `wpa_namespace` attributes as tags in logs, create a [log pipeline](https://docs.datadoghq.com/logs/log_configuration/pipelines/?tab=source) for the WPA logs and use the [Remapper](https://docs.datadoghq.com/logs/log_configuration/processors/?tab=ui#remapper). This way, in dashboards, you can create template variables for `wpa_name` and …
=> Add wpa_namespace label to metrics and split namespacedname in logs

controllers/replica_calculator.go, controllers/replica_calculator_test.go, controllers/watermarkpodautoscaler_controller.go, controllers/watermarkpodautoscaler_controller_test.go
When a target has unready pods and needs to downscale, the WPA can propose a value greater than the number of ready pods and cause an upscale event. This change prevents the upscale event from happening by not scaling at all until the proposed value is smaller than the number of ready pods.
Edge case
Create a WPA that scales on a deployment with several ready and unready pods. [Taints and tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/), [affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity), exaggerated resource requirements, etc. can be used to force unready pods. It's also easier if the WPA uses a smaller `scaleDownLimitFactor`, e.g. `15`, so that the WPA can't scale down many replicas …
=> Don't upscale when downscaling with unready pods

controllers/watermarkpodautoscaler_controller.go, controllers/watermarkpodautoscaler_controller_test.go
The delay feature does not support WPAs with multi metrics, however the feature did introduce a breaking change as it prevents scaling because a condition is added in the WPA status to reflect that the last metric evaluated was out of bounds or not.
The nominal behavior with mutli metrics is to allow scaling events even if one of the metrics is within the bounds.
fix bug introduced in 0.5.0.
=> Adding logic to skip delay if feature is not enabled

Dockerfile, go.mod
bump golang to avoid triggering CVE-2022-27664
```
➜  watermarkpodautoscaler git:(charlyf/bump-golang-1.18.6) ✗ kl watermarkpodautoscaler-66588497d4-knb2w -f
{"level":"info","ts":1663104344151.1304,"logger":"setup","msg":"Version: 0.5.2-rc.1_adb45b8"}
{"level":"info","ts":1663104344151.2458,"logger":"setup","msg":"Build time: 2022-09-13/17:22:40"}
{"level":"info","ts":1663104344151.2568,"logger":"setup","msg":"Git tag: "}
{"level":"info","ts":1663104344151.2673,"logger":"setup","msg":"Git Commit: adb45b8842d9258e76becbcaf33a9c5b5eae3c88"}
{"level":"info","ts":1663104344151.2825,"logger":"setup","msg":"Go Version: go1.18.6"}
```
=> Updating go version to 1.18.6

Makefile, controllers/replica_calculator.go, controllers/replica_calculator_test.go
Definition : 
* readinessDelaySeconds: Specifies how much time replicas need to be running for, prior to be taken into account in the scaling decisions.
Change the condition if the pod is ready and the readinessDelaySeconds is after the last transition time of the pod.
Fix the readiness_delay_sec condition.
Fix init with make intall-tools
* Create a pod with WPA and a readiness_delay_sec 120s
* Launch a load test.
* Check that the wpa service wait the readiness_delay_sec before scaling up the pod.
* Validate the test plan.
=> fix(readiness_delay_s): change condition of ignore pod

README.md, controllers/replica_calculator.go, controllers/replica_calculator_test.go, controllers/watermarkpodautoscaler_controller.go, controllers/watermarkpodautoscaler_controller_test.go
The current feature to delay scaling decision only supports one metric.
This introduces the logic necessary to support multiple metrics.
Note that for now the logic will use `OR`, so not all the metrics need to be beyond their watermarks for the duration of the delay. Further, if the union of the metrics's time beyond their respective watermarks goes longer than the configured delay, this will also allow for a scaling event to occur.
We would consider using `AND` in order to only scale if *all* metrics are beyond their respective watermarks, but it'd require a larger change with refactoring of the Status to report all the metrics's positions.
Feature Request
The best way to monitor this is by using the log: `Will not scale: value has not been out of bounds for long enough` that has the …
=> Adding support for delayScale with multi metrics

.gitignore, api/v1alpha1/watermarkpodautoscaler_types.go, api/v1alpha1/zz_generated.openapi.go, config/crd/bases/v1/datadoghq.com_watermarkpodautoscalers.yaml, config/crd/bases/v1beta1/datadoghq.com_watermarkpodautoscalers.yaml, controllers/replica_calculator.go, controllers/replica_calculator_test.go, pkg/math32/math32.go
Based on the work of @iksaif in https://github.com/DataDog/watermarkpodautoscaler/pull/160.
The goal of this PR is to introduce a feature that will have the controller attempt to converge towards a watermark of their choice.
The option is `Spec.ConvergeTowardsWatermark` and has 2 values: `lowwatermark` and `highwatermark`.
If used, when a metric is in stable regime (i.e. between its watermark), the controller will evaluate whether adding/removing `.Spec.ReplicaScalingAbsoluteModulo` would make the value of the metric lead to an unstable regime (value out of the watermarks).
The recommended value will still go through the filters (scaling velocity, min/max replicas, forbidden windows, scalingDelay).
This feature is not officially supported for multiple metrics. While the logic supports it …
=> Converging toward any watermark 

main.go
Configure a controller manager name, `wpa-controller` for the `manager` managedField. 
Previously, the `WatermarkPodAutoscaler` resource created by the wpa-controller had the managed field, `Manager: manager`, which was ambiguous and confusing. 
```
Name: example-watermarkpodautoscaler
[...]
API Version:  datadoghq.com/v1alpha1
Kind:         WatermarkPodAutoscaler
Metadata:
[...]
Managed Fields:
[...]
Manager:      manager
[...]
Manager:      manager
```
This change customizes the `Manager` name to a more meaningful name, `wpa-controller`. 
```
Name: example-watermarkpodautoscaler
[...]
API Version:  datadoghq.com/v1alpha1
Kind:         WatermarkPodAutoscaler
Metadata:
[...]
Managed Fields:
[...]
Manager:      wpa-controller
[...]
Manager:      wpa-controller
```
Anything else we should …
=> Update manager field

controllers/replica_calculator.go, controllers/replica_calculator_test.go, controllers/watermarkpodautoscaler_controller.go, controllers/watermarkpodautoscaler_controller_test.go
Several changes have been made to the autoscaling behavior and additional tests have been implemented to validate the correct function of scaling mechanisms.
- `TestReplicaCountConvergingDownward` and `TestReplicaCountConvergingDownwardBlocked` have been added to check the correct behavior when the replica count is converging downward and when this process is blocked respectively.
- `stableRegime` is introduced which tracks whether the metrics are within watermarks. 
- `canScaleAfterDelay` is modified to allow scaling events not only if the metrics have been out of bounds for a longer duration than specified in the spec, but it also takes account of `isStable` that won't block if all metrics are within watermarks.
- comprehensive test conditions have been added to verify the behavior when …
=> Modify Scaling Behavior and Implement Tests for the Convergence Towards Watermark Feature

.github/workflows/release.yaml
Fix the correct path to find the script to release the plugin.
Fixes:
```
/home/runner/work/_temp/67bcaacd-428d-4afd-bf75-b35371ccc87f.sh: line 1: ./hack/release/generate-plugin-manifest.sh: No such file or directory
Error: Process completed with exit code 127.
```
Release 060
=> Fix path in script to release plugin

controllers/replica_calculator.go, controllers/replica_calculator_test.go
During rolling updates a `maxSurge` number of pods will be created on top of what the deployment has in its spec.
This can lead to a greater number of replicas observed than expected and could even lead to unexpected scale up events.
Long term vision is to support events such as rolling updates in the lifecycle of the WPA, for now, this will allow for more sane behaviors.
Create a deployment with:
```
spec.template.spec.terminationGracePeriodSeconds: 600
```
Make sure that in the logs of the WPA, the "tolerated as ready pods" only accounts for the pods that have not been marked with a deletionTimestamp (i.e. old replicaset that has not been rotated and new replicaset maxsurge).
For a workload that has a WPA:
```
➜  ~ k get deploy alpine -ojson …
```
=> Respect Pod deletionTimestamp to avoid accounting for replicas being rotated

api/v1alpha1/const.go, controllers/watermarkpodautoscaler_controller.go, main.go
Add skipNotScalingEvents config option in WPA to disable NotScaling Kubernetes events. When disabled this will generate a log instead and update the `Status` of the WPA. 
Eliminate WPA error logs that are the result of the Kubernetes API server rate limiting WPA event writes
- When updating the `Status` we use the `ScalingActive` Condition Type. This is initially set [here](https://github.com/DataDog/watermarkpodautoscaler/blob/levipe01/notscale-events-config-option/controllers/watermarkpodautoscaler_controller.go#L687) and we override the condition & message to show that the replicas are correctly calculated, however we are choosing not to scale.
- Leaving the default behavior to continue to write Kubernetes Events in the event that 3rd party users are currently monitoring on these.
- …
=> Make generating NotScale events configurable; use logs when disabled

controllers/metrics.go, controllers/watermarkpodautoscaler_controller.go
Motivation
----------
Currently the wpa controlleur is only exposing a logs to inform of any upscale/downscale. It would be very useful to have a metric on upscale/downscale in order to be able to visualize them.
see: https://github.com/DataDog/watermarkpodautoscaler/blob/9adcbcf5a9df4bb6b4370820dead417afa7c6932/controllers/watermarkpodautoscaler_controller.go#L379
Scope
------
Create two count metrics:
- `watermarkpodautoscaler.wpa_controller_upscale_replicas_total`: count the number of upscale done
- `watermarkpodautoscaler.wpa_controller_downscale_replicas_total`: count the number of down scale
A brief description of the change being made with this pull request.
Write there any instructions and …
=> metrics: add count for number of upscale and downscale

.github/workflows/build.yaml, .github/workflows/release.yaml
update the CI configuration to use new goreleaser parameter options instead of the deprecated options
`--skip-publish` and `--skip-validate` arguments are deprecated in favour of `--skip=publish` and --skip=validate
an example of a failing job https://github.com/DataDog/watermarkpodautoscaler/actions/runs/9570721706/job/26386235301 
=> fix(ci): use new goreleaser parameter

.gitlab-ci.yml, Makefile
Use the `registry.ddbuild.io` registry instead of directly the internal ECR.
Update the makefile to use buildx now.
Migrate to more recent gitlab docker runner
=> fix(ci): migrate to registry.ddbuild.io for ci images

main.go
Add a new wpa-controller parameter to set the duration of the kube-apiserver client timeout.
This parameter can be usefull in some environment when the api-server takes time to reply.
It should avoid having the controller in a bad shape.
N/A
Not easy to test the impact of this new parameter with a working API-server.
=> Add the possibility to configure the api-server client timeout

controllers/watermarkpodautoscaler_controller_test.go
PR adds verification for metrics in reconciler test. `wantPromMetrics` are just baselines for current tests and isn't verified for correctness (first three are interesting since they are all 0).
Reviewing https://github.com/DataDog/watermarkpodautoscaler/pull/187. 
=> Add Prometheus metrics verification to reconciler test

Makefile, apis/datadoghq/v1alpha1/zz_generated.openapi.go
Fix the generation of OpenAPI.
It has accidentally been broken by the upgrade of `openapi-gen` in #221.
None: the generated `GetOpenAPIDefinitions` function is used nowhere.
=> Fix the generation of OpenAPI

controllers/datadoghq/metrics.go, controllers/datadoghq/recommender.go, controllers/datadoghq/recommender_test.go
Fix recommender metrics ("recommender" != "client")
=> recommender: fix instrumentation and add tests

.gitlab-ci.yml
On `main` the build failed on gitlabci only.
It seems to be due to a corruption on the cache using in gitlab to optimise the ci jobs. 
this PR attempt to fix the ci build by removing the usage of the cache.
Fix CI to be able to release a version of WPA controller
I suppose that the cache is corrupted because some jobs are using golang 1.22 and other 1.23 (with `ci-containers-project:v3.0.0` image). 
I'm working on a new `ci-containers-project` image that use golang 1.22 to do other tests and put back the CI cache.
we can see that the build job is working on this branch https://gitlab.ddbuild.io/DataDog/watermarkpodautoscaler/-/jobs/721815005
=> fix: remove temporary gitlab cache to fix ci build

LICENSE-3rdparty.csv, controllers/datadoghq/watermarkpodautoscaler_controller.go, controllers/datadoghq/watermarkpodautoscaler_controller_test.go, go.mod, go.sum, main.go
Removes the dependency on the datadog-operator project.
The WPA only depends on the datadog-operator to get the DatadogMonitor CRD for the "Lifecycle control" feature introduced in this PR: https://github.com/DataDog/watermarkpodautoscaler/pull/202 
However, the WPA only needs to access one specific field within the monitor. Therefore, using Kubernetes "unstructured" objects to interact with this CRD is a feasible solution.
We'd like to avoid the dependency from the datadog-operator because dependencies between projects that require kubernetes libraries can be problematic. Sometimes, in order to upgrade the kubernetes dependencies in one project, we need to upgrade the other project first, and we'd like to avoid this situation so that each project can be upgraded independently.
Until now …
=> [controllers/wpa] Remove dependency from datadog-operator by using Unstructured

controllers/datadoghq/recommender.go, controllers/datadoghq/replica_calculator.go, controllers/datadoghq/replica_calculator_test.go, controllers/datadoghq/watermarkpodautoscaler_controller.go
The recommender needs to advertise the current cluster name in the request.
This is required to have a fully qualified kubernetes target ref in multi-cluster environments.
The cluster is optional as it's only needed in setups using the recommender and multiple k8s clusters.
=> recommenders: attach the current cluster name

controllers/datadoghq/recommender.go, controllers/datadoghq/recommender_test.go
This fixes the WorkloadRecommendationRequest target to have correct `UpperBound` and `LowerBound` values (float64) when the incoming RecommenderSpec has lower than 1.0 low or high watermarks.
It wasn't possible to have:
```
apiVersion: datadoghq.com/v1alpha1
kind: WatermarkPodAutoscaler
metadata:
name: koutris-storage-metrics-intake-az0
namespace: koutris
spec:
...
recommender:
highWatermark: "0.8"
lowWatermark: "0.4"
settings:
worker_group: koutris-storage-metrics-intake-az0
targetType: memory
url: https://shard-orchestrator-api.rapid-shard-orchestrator.all-clusters.local-dc.fabric.dog:8443/autoscaling/recommendation
...
```
The Recommender API request that was triggered was:
```
{
"targetRef": {
...
},
...
"targets": [
{
"type": "memory"
}
],
"settings": {
"worker_group": …
```
=> Fix recommender API low/high watermark handling when < 1

controllers/datadoghq/recommender.go, controllers/datadoghq/recommender_test.go
Otherwise we end up with many timeseries as the label value keeps changing
=> recommender: make sure the metric name is stable

controllers/datadoghq/recommender.go, controllers/datadoghq/recommender_test.go, controllers/datadoghq/replica_calculator.go, controllers/datadoghq/watermarkpodautoscaler_controller.go
This makes sure we get the proper value for the `metric` field and metrics in the WPA (before this change the replica count was used instead)
=> recommender: propagate the observed value to the status

chart/watermarkpodautoscaler/Chart.yaml
Bump WPA chart version to v0.5.0 for the changes added in https://github.com/DataDog/watermarkpodautoscaler/pull/221.
Reconcile Chart version and Changelog version discrepency. 
=> Bump WPA chart version to v0.5.0

chart/watermarkpodautoscaler/CHANGELOG.md, chart/watermarkpodautoscaler/Chart.yaml, chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd_v1.yaml, chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd_v1beta1.yaml
This also fixes the CRD that are in the chart.
In commit cd5a4925, I forgot to update the alongside chart provided with WPA.
It's not clear if this is needed because the chart depends on datadog CRD which I have no idea how they are built.
Also not clear if the chart version needs to be bumped (there's a discrepancy between the changelog and the chart version.
This was tested by modifying directly the CRD in an experimental cluster.
=> Update example chart with new CRD definitions

controllers/datadoghq/replica_calculator.go, controllers/datadoghq/replica_calculator_test.go, controllers/datadoghq/watermarkpodautoscaler_controller.go, controllers/datadoghq/watermarkpodautoscaler_controller_test.go
It bubbles up the recommender reason to the WPA Status for ConditionValidMetricFound.
When using `kubectl describe wpa` it would be great to see the reason the recommender returned an given replica number. This is very useful for troubleshooting (compared to looking at logs).
This is missing tests at the reconciler level. Will probably add some if time allows.
This was tested succesfully on chillpenguin and oddish-a:
```
Conditions:
Last Transition Time:  2025-01-14T15:53:35Z
Message:               the last scaling time was sufficiently old as to warrant a new scale
Reason:                ReadyForScale
Status:                True
Type:                  AbleToScale
Last Transition Time:  2025-01-14T15:53:35Z
Message:               the WPA was able to successfully calculate a replica count …
```
=> Use recommender reason to decorate reconciler status

controllers/datadoghq/replica_calculator.go, controllers/datadoghq/replica_calculator_test.go
It fixes a bug where the recommender `upperReplicas` and `lowerReplicas` were reversed when calling `adjustReplicaCount`.
With the lower and upper bound reversed it would prevent some downscale (and possibly upscale) scenarios to happen, because the returned `metricPosition` would have both `isAbove=true` and `isBelow=true`. This in turn would confuse the rest of the algorithm, especially the component that tried to converge toward one of the watermark.
It's hard to test, but the fix is very simple.
It was spot because of this log parameters that show the reverse:
In that example, the deployment was at 40 pods which was within bounds but in the higher part of the bounds and WPA wasn't trying to downscale producing this error:
```
Scaling down would likely make the usage go above the High …
```
=> Fix lower/upper bound inversion in recommender replica calculation

.github/workflows/release.yaml
update 2 deprecated github actions:
- upload-artifact from v3 to v4
- download-artifact from v3 to v4
fix release process to finalise v0.9.0 release
error info: https://github.com/DataDog/watermarkpodautoscaler/actions/runs/12936581622 
Official communication https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/ 
=> Fix release github worflow

controllers/datadoghq/replica_calculator.go, controllers/datadoghq/watermarkpodautoscaler_controller.go
- err can be nil when `requeueAfterForWPAErrors` is called
- low/high watermakrs can be 0
We found a panic in our test env
=> Fix two panics

controllers/datadoghq/replica_calculator.go, controllers/datadoghq/replica_calculator_test.go
The PR fixes a bug related to the `minAvailableReplicaPercentage` option and evicted pods.
> **minAvailableReplicaPercentage:** Indicates the minimum percentage of replicas that need to be available in order for the controller to autoscale the target. For instance, if set at 50 and less than half of the pods behind the target are in an Available state, the target will not be scaled by the controller.
According to the [Kubernetes Documention](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/)
> During a node-pressure eviction, the kubelet sets the [phase](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase) for the selected pods to Failed, and terminates the Pod. 
Because evicted pods remain in the `Terminated` state until garbage …
=> Fix Evicted Pods Skewing Available Replicas Calculation

.gitlab-ci.yml
Add a gitlab job to trigger fips enabled image
Same change as [this one](https://github.com/DataDog/extendeddaemonset/commit/e1e56cb179a2d4f1605967c8a1f6d6c299a57ef8) made to the extendeddaemonset
Relies on [this PR](https://github.com/DataDog/images/pull/6780)
=> Add Gitlab job for building FIPS enabled image for GovCloud

.github/workflows/release.yaml
Use GITHUB_TOKEN for getting last release version in the github action release workflow.
the goal is to avoid rate limit during releasing like this occurence: https://github.com/DataDog/watermarkpodautoscaler/actions/runs/13819715791/job/38661833976
=> fix(releasing): use github token for getting the last release tag

controllers/datadoghq/metrics.go, controllers/datadoghq/recommender.go, controllers/datadoghq/watermarkpodautoscaler_controller.go, controllers/datadoghq/watermarkpodautoscaler_controller_test.go
This adds:
- per WPA `scaling_active` that reflects the value of the associated condition
- per HTTP client `http_client_requests_errors_total` to count client errors (and not http errors)
Detect WPAs that might have trouble contacting their recommenders
=> Add more metrics to detect broken WPAs

.gitlab-ci.yml, Dockerfile, Makefile, pkg/util/fipsonly.go
This change updates the dockerfile and build scripts to allow building a fips-compliant version of the WPA image
The bulk of the changes were copied over from [the similar change](https://github.com/DataDog/datadog-operator/pull/1731) made to the datadog-operator repo
More details on testing can be found in this [images PR](https://github.com/DataDog/images/pull/6944)
=> Generate fips image compiled with Go boringcrypto

.gitlab-ci.yml
Remove global gitlab cache
The build consistently fails on main since this was re-introduced [here](https://github.com/DataDog/watermarkpodautoscaler/pull/237)
More investigation needs to be done as to why, but in the interim the goal is to fix builds on main
[CI history over the last 6 months](https://app.datadoghq.com/ci/pipeline-executions?query=ci_level%3Apipeline%20%40ci.pipeline.name%3A%22DataDog%2Fwatermarkpodautoscaler%22%20%40git.branch%3Amain&agg_m=count&agg_m_source=base&agg_t=count&colorBy=meta%5B%27ci.stage.name%27%5D&colorByAttr=meta%5B%27ci.stage.name%27%5D&currentTab=trace&fromUser=true&graphType=span_list&index=cipipeline&spanViewType=metadata&start=1728583428248&end=1744135428248&paused=false), note that the only time main succeeded was during the small window where the …
=> Remove global gitlab cache

README.md
Add a note to the README explaining why you shouldn't set replicas in the deployment, and the issues you may see if you do.
If you set the `replicas` value on your deployment, then every time you apply the deployment, the number of replicas will be reset to that value. This will cause a race between the Kubernetes controller and WPA in setting the number of replicas and fluctuate the number down and up when you apply the deployment.
N/A
N/A
=> doc(README): Update docs to explain why you shouldn't set replicas in the deployment

controllers/datadoghq/replica_calculator.go
This pull request modifies the logic for determining the metric name in the `ReplicaCalculator`, we don't want the URL as a tag here we want a recommender name we compute from the settings.
=> Fix the metric_name: label when using a recommender

.github/chainguard/self.pr-backport.create-pr.sts.yaml, .github/workflows/pr-backport.yaml
This is part of an initiative lead by SDLC security to [harden Github security settings](https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/3913581900/GitHub+Workflow+Token+Permissions+GITHUB_TOKEN). To do so, we need to move away from GITHUB_TOKEN having the permission to approve and merge PRs, which is a behaviour we see in this repo.
Instead, [dd-octo-sts](https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/4705912130/DD+Octo+STS) is an alternative to provide ephemeral scoped tokens delivering the same features with improved security.
This PR implements the migration to dd-octo-sts.
=> [SINT-3862] on-board to dd-octo-sts
