pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go

In case of `reconcileWPA` error, we need to requeue the Resource in order to retry to process it again. We put a delay of 1 second in order to not retry directly and limit the number of retries if it only a transient issue.

handle reconcileWPA error with an item requeue

---

README.md

editing the readme for grammar and readability

---

README.md

🐛 a 404 fix
📝 some documentation about the `dryRun` flag
📝 a clarification on the precedence of `minReplicas` and `maxReplicas`
🎨 some code fences with their language

:memo: Doc update

---

.github/CODEOWNERS
README.md
chart/watermarkpodautoscaler/.helmignore
chart/watermarkpodautoscaler/Chart.yaml
chart/watermarkpodautoscaler/templates/_helpers.tpl
chart/watermarkpodautoscaler/templates/api_resource_rbac.yaml
chart/watermarkpodautoscaler/templates/clusterrole.yaml
chart/watermarkpodautoscaler/templates/clusterrole_binding.yaml
chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd.yaml
chart/watermarkpodautoscaler/templates/deployment.yaml
chart/watermarkpodautoscaler/templates/role.yaml
chart/watermarkpodautoscaler/templates/role_binding.yaml
chart/watermarkpodautoscaler/templates/serviceaccount.yaml
chart/watermarkpodautoscaler/values.yaml

- Add Helm Chart
- Add deployment documentation
- Define project codeowners

Add Helm Chart

---

README.md

Add some troubleshooting notes for the Cluster Agent to enable the WPA listener and to be able to watch the WPA objects

Added troubleshooting notes for the cluster agent configuration

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Add `.github/ISSUE_TEMPLATE.md` and `.github/PULL_REQUEST_TEMPLATE.md`
More details, easier QA

Add PR and issue templates

---

chart/watermarkpodautoscaler/templates/clusterrole.yaml
deploy/clusterrole.yaml

Add the required RBAC to run the Resource Type WPAs
Resource Type WPAs were not working

Fix WPA Resource type RBAC

---

examples/external-type.yaml
examples/resource-type.yaml

Add resource type example in addition to the external type example explained in the readme

Add example CRs

---

README.md

Mention how to enable WPA in the DCA using helm
Complete this https://github.com/DataDog/watermarkpodautoscaler/pull/47

Add DCA helm chart instruction

---

cmd/manager/main.go

The WPA as is can't run in HA with a health probe, because of the blocking channel to know if the controller is the leader.
In other projects we have introduced a metric on top of relying on the leaderelection logic in the controller manager (not starting the Runnables if the controller is not the leader), then we rely on the metrics endpoint for health.
I decided to add a health check to be used as a health probe and add the ability to enable or not the leader election.
Note that if the leader loses the election, the pod will be rotated. I find this behaviour suboptimal because it does not take full advantage of the concept. However, because the upstream lib does not have logic process re-election, it is what is best.
Case 1: delete the CM lock until the follower wins the election. The …

Add logic to rely on leaderelection from controller manager

---

main.go

- Set a shorter resync default period (10h -> 1h)
- Make it configurable via the `syncPeriodSeconds` flag
Reprocess missed events more quickly
The Manager `SyncPeriod` documentation:
```
SyncPeriod determines the minimum frequency at which watched resources are reconciled.
A lower period will correct entropy more quickly, but reduce responsiveness to change if there are many watched resources.
Change this value only if you know what you are doing.
Defaults to 10 hours if unset. there will a 10 percent jitter between the SyncPeriod of all controllers so that all controllers will not send list requests simultaneously.
```
No obvious way to test this, it's a config for the `controller-runtime` internals

Set a shorter resync period (10h -> 1h)

---

.gitlab-ci.yml
README.md
RELEASING.md

Pull request to prepare the renaming of the "master" branch to "main"
Next steps:
* merge the PR on "master"
* rename the branch to `main` thanks to the github UI

default branch is now main

---

.gitlab-ci.yml

Add `docker login` for the CI jobs.
Fix CI build due to dockerhub rate limit policy

Fix docker ratelimit in CI

---

config/rbac/role.yaml
config/rbac/role_binding.yaml
controllers/watermarkpodautoscaler_controller.go

- Fix rbac's api groups
- Fix role binding name
Fix `make deploy`
`make deploy` should succeed + the controller works without any rbac errors

Fix rbacs and make deploy

---

controllers/watermarkpodautoscaler_controller.go

`scale.NewForConfig` modifies given config pointer, overriding fields such as GV and Serializer, having an impact on serializer config used by `controller-runtime` watchers.
Run WPA, you should not see any error similar to:
```
1 reflector.go:436] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: watch of *v1alpha1.WatermarkPodAutoscaler ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"WatermarkPodAutoscaler\" is registered for version \"datadoghq.com/v1alpha1\" in scheme \"pkg/runtime/scheme.go:100\"") has prevented the request from succeeding
```

Fix unable to decode watch event error

---

Makefile
config/manager/kustomization.yaml
config/manager/manager.yaml
go.mod
main.go

A brief description of the change being made with this pull request.

fix logs timestamp format

---

api/v1alpha1/watermarkpodautoscaler_default.go
controllers/watermarkpodautoscaler_controller_test.go

Unlimited ScaleUpLimitFactor
FR
Apply a WPA with ScaleUpLimitFactor > 100

Unlimited ScaleUpLimitFactor

---

.github/workflows/validation.yaml

Run e2e tests on different k8s versions
Extend the test coverage
E2E jobs are green

[CI] Add kube versions matrix

---

README.md

Fixes the example WPA in the README.
`kubectl apply -f` with the example of the README should not show any errors.

[README] Fix example WPA

---

cmd/kubectl-wpa/app/dryrun/dryrun.go

introduce the option `--all-namespace` in the `kubectl wpa` plugin to search WPA instance in all namespaces
improve UX experience.
```
➜ ./bin/kubectl-wpa dry-run list -l app=example  -o csv       
default,example1-watermarkpodautoscaler,enabled
default,example2-watermarkpodautoscaler,enabled
➜ ./bin/kubectl-wpa dry-run list -l app=example  -o csv --all-namespaces
default,example1-watermarkpodautoscaler,enabled
default,example2-watermarkpodautoscaler,enabled
ns3,example3-watermarkpodautoscaler,disabled
```

feat(plugin): add --all-namespaces option

---

controllers/watermarkpodautoscaler_controller.go

Increases the requeue delay for "scale not found" errors.

[controller] Increase requeue delay for "scale not found" errors

---

controllers/replica_calculator.go
controllers/replica_calculator_test.go

previously the way we computed the list of pod ready corresponding
to a WPA was not enough precise. In some case if 2 deployments in
the same Namespace was using the same Selector can trigger a bug
in the wpa where both deployment's pods are taken into account when
calculating the current replicas value.

fix: improve how we filter pods from other deployments

---

api/v1alpha1/watermarkpodautoscaler_types.go
api/v1alpha1/zz_generated.openapi.go
controllers/watermarkpodautoscaler_controller.go

A brief description of the change being made with this pull request.

feat: improve WPA status output with lastCondition info

---

README.md

[doc] Update kubectl plugin link in README.md

---

README.md

Updating Readme of the WPA controller

---

controllers/replica_calculator.go

Log replica calculation results for each metric.

Levan m/log replica calculations

---

controllers/replica_calculator.go

```
Status:
Conditions:
[...]
Last Transition Time:  2023-01-27T13:12:58Z
Message:               Allow downscaling if the value stays under the Watermark
Reason:                Value above Low Watermark
Status:                True
Type:                  BelowLowWatermark
```

Fix typo in LW reason

---

.gitlab-ci.yml

Similar to https://github.com/DataDog/datadog-operator/pull/727

Fixing job image

---

.github/workflows/build.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/release.yaml
.github/workflows/validation.yaml

centralised golang version in the different github action.
try to fix build error in PR #182 

update go version in github actions

---

.github/workflows/build.yaml
.github/workflows/release.yaml
.golangci.toml
Makefile
cmd/kubectl-wpa/app/common/client.go

* Update golangci-lint to `v1.51.0` to support go `v1.20`
* Remove duplicate word caught by linter
* Update disabled linters list
* Fix github workflows

Update golangci-lint and github workflows

---

README.md

document the new option `logs-attributes`

Adding entry to document the annotation to add kv in the logs

---

README.md

Clarify support of multiple metrics in the readme.

Clarify support of multiple metrics in FAQ

---

.github/workflows/release.yaml

Release fails at the moment since it uses the wrong path.

Fix changelog path for the release

---

.github/workflows/pr-linter.yaml

Adding a pr linter github workflow similar to the ones we have for the operator and eds

Add pr linter workflow

---

.github/CODEOWNERS

use @DataDog/wpa-maintainers as team for code review since the ownership will be progressively moved to a new team or squad
Allow new contributors outside @DataDog/container-ecosystems  to review pull request

Update CODEOWNERS to use wpa-maintainers team for code review

---

Makefile
hack/patch-chart.sh

Fix `yq` in `patch-chart.yaml`, w is unrecognized option.

Fix yq command in patch-chart.sh

---

controllers/datadoghq/metrics.go

Register the metrics that was added by the PR #210
the feature implemented by #210 didn't work as expected

fix: add missing metrics registration

---

controllers/metrics.go

backport #215: fix: add missing metrics registration

---

controllers/datadoghq/watermarkpodautoscaler_controller_test.go

Update WPA controller unit test to check new upscale-downscale metrics
The commit also modify the way the unit tests valid the generated metrics that the
controller emit when it does an action. Now the unit-tests will only validate
the metric values that are provided inside the "wantPromMetrics" or each test.
Improve test coverage link to the PR #210

Update WPA controller unittest to check new upscale-downscale metrics

---

chart/watermarkpodautoscaler/templates/deployment.yaml
chart/watermarkpodautoscaler/templates/role.yaml
chart/watermarkpodautoscaler/values.yaml

Now that the command line argument and configmap support has been removed, update the chart too.

Update the chart

---

.github/workflows/build.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/pr-linter.yaml
.github/workflows/release.yaml
.github/workflows/validation.yaml

VULN-8306
A brief description of the change being made with this pull request.

Configure Github workflow and job level permissions

---

service.datadog.yaml

Add watermarkpodautoscaler service file.
We want to setup conductor for wpa; this requires the service file living in the `watermarkpodautoscaler` repository.
Using a test branch etc. for now to allow for testing as this is being setup

Add watermarkpodautoscaler service file

---

service.datadog.yaml

Set up conductor to build and test WPA nightly. Updates previous PR to use normal wpa channels.
We want to ensure that wpa can always be built / passes tests. 

Setup nightly build

---

.github/workflows/pr-linter.yaml
.github/workflows/release.yaml

use the new method to get a github_token in github actions

fix: github token in github actions

---

.github/workflows/pr-linter.yaml
.github/workflows/release.yaml

DD_GITHUB_TOKEN_GENERATOR_APP_ID is define as `secret` and not `var` in this project
Fix CI jobs

fix app-id in github actions

---

.github/workflows/pr-linter.yaml
.github/workflows/release.yaml

Fallback to a "static" token in github action for now, until we have the github app properly set in this repo
error still present in the `actions/create-github-app-token`
```
Run actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69
owner and repositories not set, creating token for the current repository ("watermarkpodautoscaler")
Failed to create token for "watermarkpodautoscaler" (attempt 1): error:1E08010C:DECODER routines::unsupported
Failed to create token for "watermarkpodautoscaler" (attempt 2): error:1E08010C:DECODER routines::unsupported
Failed to create token for "watermarkpodautoscaler" (attempt 3): error:1E08010C:DECODER routines::unsupported
Failed to create token for "watermarkpodautoscaler" (attempt 4): error:1E08010C:DECODER routines::unsupported
Error: …
```

fallback to static token for now

---

.gitlab-ci.yml

reintroduce gitlabci cache
cache was removed in #235 
now, with the new `ci-containers-project` image it should be fine

reintroduce gitlabci cache

---

.github/workflows/pr-backport.yaml

Add a github action to create automatically backport PR from another PR done on `main`
Simplify PR backport during releasing

add pr backport script

---

.gitlab-ci.yml

Update internal image template version to v3

Update internal image template version to v3

---

controllers/datadoghq/replica_calculator.go
controllers/datadoghq/watermarkpodautoscaler_controller.go

- Make sure it works with `kubectl wpa`
- Use the correct value for the prometheus metric

recommender: adjust metric display

---

test/e2e/metricsserver/metricsserver.go

fix: Fix problematic error returns

---

controllers/datadoghq/watermarkpodautoscaler_controller.go

Otherwise failing to get the metric will result in the conditions to be modified and might prevent upscale/downscales by reseting the cooldowns

Handle metric computations errors and don't reset conditions

---

README.md

Currently the documentation could mislead readers into thinking `tolerance` is added/subtracted to/from high/low watermarks. But what is added/subtracted is not the `tolerance` itself.
Remove possible source of confusion from documentation

Clarify how 'tolerance' is used in computing the desired replicas

---

.github/workflows/release.yaml

In the release workflow, add the Github token to the action https://github.com/marketplace/actions/get-latest-release 
avoid rate limit during WPA controller release.

Update release.yaml add token for release action
